
from typing import Any
from typing import Literal
from typing import overload

from gi.repository import Gtk



class Builder: ...


class SearchViewBuilder(Builder):

    filename: str = ...

    @overload
    def get(self, name: Literal['search_entry']) -> Gtk.Entry: ...
    @overload
    def get(self, name: Literal['date_hint']) -> Gtk.Label: ...
    @overload
    def get(self, name: Literal['search_checkbutton']) -> Gtk.CheckButton: ...
    @overload
    def get(self, name: Literal['header_box']) -> Gtk.ListBox: ...
    @overload
    def get(self, name: Literal['header_name_label']) -> Gtk.Label: ...
    @overload
    def get(self, name: Literal['header_date_label']) -> Gtk.Label: ...
    @overload
    def get(self, name: Literal['result_row_grid']) -> Gtk.Grid: ...
    @overload
    def get(self, name: Literal['row_name_label']) -> Gtk.Label: ...
    @overload
    def get(self, name: Literal['row_avatar']) -> Gtk.Image: ...
    @overload
    def get(self, name: Literal['row_time_label']) -> Gtk.Label: ...
    @overload
    def get(self, name: Literal['results_listbox']) -> Gtk.ListBox: ...
    @overload
    def get(self, name: Literal['search_box']) -> Gtk.Box: ...
    def get(self, name: str) -> Any:
        pass
