repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff-check
        exclude: ".githooks/"
      - id: ruff-format
      - id: ruff-check
        args: [--select, I, --fix]

  - repo: https://codeberg.org/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse-lint-file

  - repo: https://github.com/crate-ci/typos
    rev: v1.50.3
    hooks:
      - id: typos
