.TH Gajim 1 "December  19, 2004"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
Gajim \- jabber client
.SH SYNOPSIS
.B gajim [\-c] [\-h]
.SH DESCRIPTION
.B Gajim 
is a jabber client. While this is a work in progress and by far not complete, 
it is already working nicely. For more information on jabber, see 
www.jabber.org (or the jabber package which contains the jabber server 
software).
.PP
.SH OPTIONS
.TP
\fB\-c\fR
Run Gajim as a client of another Gajim.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help.
.SH AUTHOR
Written by Yann Le Boulanger <asterix@lagaule.org> and Vincent Hanquez <tab@snarc.org>.
