.\" 20050509
.TH "Gajim" "1" "May  15, 2005" "Gajim dev team" ""
.SH "NAME"
Gajim \- a jabber client
.SH "SYNOPSIS"
.B gajim [\-c] [\-h]
.SH "DESCRIPTION"
.B Gajim 
is a jabber client written in PyGTK and released under the GNU GPL. While this is a work in progress and by far not complete, 
it is already working nicely. For more information on jabber, see 
www.jabber.org and on Gajim see www.gajim.org.
.PP 
.SH "OPTIONS"
.TP 
\fB\-c\fR
Run Gajim as a client of another Gajim.
.TP 
\fB\-h\fR, \fB\-\-help\fR
Print this help.
.SH "FEEDBACK"
You can report bugs or features request in http://trac.gajim.org or in the mailing list: https://lists.gajim.org/cgi\-bin/listinfo/gajim\-devel
.SH "AUTHORS"
Written by Yann Le Boulanger <asterix@lagaule.org>, Vincent Hanquez <tab@snarc.org> and Nikos Kouremenos <kourem@gmail.com>.
