.\" 20050901
.TH "Gajim-history-manager" "1" "September 01, 2005" "Gajim dev team" ""
.SH "NAME"
Gajim-history-manager \- Tool to manage gajim logs
.SH "SYNOPSIS"
.B gajim-history-manager [\-c config-path] [\-h]
.SH "DESCRIPTION"
.B Gajim-history-manager
is a tool to manage (do some cleanup) log file of Gajim jabber client.
.PP 
.SH "OPTIONS"
.TP 
\fB\-c\fR, \fB\-\-config-path\fR path
Path where logs.db is located. ~/.gajim by default.
.TP 
\fB\-h\fR, \fB\-\-help\fR
Print this help.
.SH "FEEDBACK"
You can report bugs or feature requests in http://trac.gajim.org or in the mailing list: http://lists.gajim.org/cgi\-bin/listinfo/gajim\-devel. You can also find us in our room gajim@conference.gajim.org
.SH "AUTHORS"
Written by Yann Le Boulanger <asterix@lagaule.org>, Nikos Kouremenos <kourem@gmail.com> and Dimitur Kirov <dkirov@gmail.com>.
