[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Hidden=true

Directories=scalable/apps,scalable/categories,scalable/devices,scalable/status

[scalable/apps]
Size=128
MinSize=16
MaxSize=256
Context=Applications
Type=Scalable

[scalable/categories]
Size=128
MinSize=16
MaxSize=256
Context=Categories
Type=Scalable

[scalable/devices]
Size=128
MinSize=16
MaxSize=256
Context=Devices
Type=Scalable

[scalable/status]
Size=128
MinSize=16
MaxSize=256
Context=Status
Type=Scalable
