.\" 20050901
.TH "Gajim" "1" "September 01, 2005" "Gajim dev team" ""
.SH "NAME"
Gajim \- a jabber client
.SH "SYNOPSIS"
.B gajim [\-v] [\-p] [\-h]
.SH "DESCRIPTION"
.B Gajim 
is a jabber client written in PyGTK and released under the GNU GPL. For more information on jabber, see 
http://www.jabber.org and on Gajim see http://www.gajim.org
.PP 
.SH "OPTIONS"
.TP 
\fB\-p\fR, \fB\-\-profile\fR name
Run Gajim using ~/.gajim/config.name
.TP 
\fB\-v\fR, \fB\-\-verbose\fR
Print xml stanzas and other debug information.
.TP 
\fB\-h\fR, \fB\-\-help\fR
Print this help.
.SH "FEEDBACK"
You can report bugs or feature requests in http://trac.gajim.org or in the mailing list: https://lists.gajim.org/cgi\-bin/listinfo/gajim\-devel. You can also find us in our room gajim@conference.gajim.org
.SH "AUTHORS"
Written by Yann Le Boulanger <asterix@lagaule.org>, Nikos Kouremenos <kourem@gmail.com> and Dimitur Kirov <dkirov@gmail.com>.
