.Dd January 21, 2018
.Dt GAJIM-HISTORY-MANAGER 1 URM
.Os UNIX
.Sh NAME
.Nm gajim-history-manager
.Nd a tool to manage
.Xr gajim 1
logs
.Sh SYNOPSIS
.Nm
.Fl h
.Nm
.Op Fl c Ar directory
.Sh DESCRIPTION
.Nm
is a tool to manage
.Po do some cleanup Pc log file of
.Xr gajim 1 .
Use this program to delete or export logs.
For more information on database logs see <https://trac.gajim.org/wiki/LogsDatabase>.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h Fl Fl help
Show help options
.It Fl c Fl Fl config-path Em directory
Where to look for logs file
.El
.Sh FILES
.Bl -tag -width Ds
.It $XDG_DATA_HOME/gajim/logs.db
The history database log file used when
.Op Fl c
is not specified.
.El
.Sh AUTHORS
.An -nosplit
.Nm
is written and maintained by
.An Yann Leboulanger ,
and
.An Denis Fomin ,
with contributions and patches merged from many individuals around the world.
See files
.Pa AUTHORS
and
.Pa THANKS ,
for a complete list.
.Sh COPYRIGHT
Copyright (C) 2003-2021 Gajim Team
.Pp
.Nm
is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 3 only.
.Pp
.Nm
is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.Pp
You should have received a copy of the GNU General Public License along with
.Nm .
If not, see <https://www.gnu.org/licenses/>.
.Sh FEEDBACK
You can report bugs or feature requests in our bug tracker at
.Em https://dev.gajim.org/gajim/gajim/issues
or in the
.Em gajim-devel
mailing list; if you want to send us a patch, please do so in our bug tracker.
You can also find us in our chat room.
.Sh WWW
https://www.gajim.org/
.Sh XMPP
You are welcome to join us at gajim@conference.gajim.org
.Sh MAILING LIST
Below are public mailing lists on lists.gajim.org
.Bd -literal -offset indent
https://lists.gajim.org/cgi-bin/listinfo/gajim-devel
https://lists.gajim.org/cgi-bin/listinfo/translators
.Ed
.Pp
More mailing lists at
.Bd -literal -offset indent
https://lists.gajim.org/cgi-bin/listinfo
.Ed
.Sh BUGS
Please submit bugs at https://dev.gajim.org/gajim/gajim/issues
.Sh SEE ALSO
.Xr gajim 1
.Xr gajim-remote 1
