.Dd January 21, 2018
.Dt GAJIM-REMOTE 1 URM
.Os UNIX
.Sh NAME
.Nm gajim-remote
.Nd a remote control utility for
.Xr gajim 1
.Sh SYNOPSIS
.Nm
.Ar command
.Sh DESCRIPTION
.Nm
is a script to control and communicate with a running instance of
.Xr gajim 1
by D-Bus.
.Sh OPTIONS
.Bl -tag -width Ds
.It Available commands
.El
.Ss account_info Aq account
Gets detailed info on a account
.Ss change_status Bo status Bc Bo message Bc Bq account
Changes the status of account or accounts
.Ss check_gajim_running
Check if Gajim is running
.Ss contact_info Aq jid
Gets detailed info on a contact
.Ss get_status Bq account
Returns current status (the global one unless account is specified)
.Ss get_status_message Bq account
Returns current status message (the global one unless account is specified)
.Ss get_unread_msgs_number
Returns number of unread messages
.Ss help Bq command 
Shows a help on specific command
.Ss list_accounts
Prints a list of registered accounts
.Ss list_contacts Bq account
Prints a list of all contacts in the roster. Each contact appears on a separate line
.Ss remove_contact Ao jid Ac Bq account
Removes contact from roster
.Ss send_chat_message Ao jid Ac Ao message Ac Bo PGP key Bc Bq account
Sends new chat message to a contact in the roster. Both OpenPGP key and account are optional. If you want to set only 'account', without 'OpenPGP key', just set 'OpenPGP key' to ''.
.Ss send_file Ao file Ac Ao jid Ac Bq account
Sends file to a contact
.Ss send_groupchat_message Ao room_jid Ac Ao message Ac Bq account
Sends new message to a groupchat you've joined.
.Ss send_single_message Ao jid subject Ac Ao message Ac Bo PGP key Bc Bq account
Sends new single message to a contact in the roster. Both OpenPGP key and account are optional. If you want to set only 'account', without 'OpenPGP key', just set 'OpenPGP key' to ''.
.Ss send_xml Ao xml Ac Bq account
Sends custom XML
.Ss set_priority Ao priority Ac Bq account
Changes the priority of account or accounts
.Ss show_next_pending_event
Pops up a window with the next pending event
.Ss toggle_roster_appearance
Shows or hides the roster window
.Sh EXAMPLES
Open a URI of group chat gajim
.Pp
.Dl $ gajim-remote handle_uri xmpp:gajim@conference.gajim.org?join
.Pp
Send custom XML
.Pp
.Dl $ gajim-remote send_xml $(cat Pa filename.xml ) Qq your@jabber.id
.Sh AUTHORS
.An -nosplit
.Nm
is written and maintained by
.An Yann Leboulanger ,
and
.An Denis Fomin ,
with contributions and patches merged from many individuals around the world.
See files
.Pa AUTHORS
and
.Pa THANKS ,
for a complete list.
.Sh COPYRIGHT
Copyright (C) 2003-2022 Gajim Team
.Pp
.Nm
is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 3 only.
.Pp
.Nm
is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.Pp
You should have received a copy of the GNU General Public License along with
.Nm .
If not, see <https://www.gnu.org/licenses/>.
.Sh FEEDBACK
You can report bugs or feature requests in our bug tracker at
.Em https://dev.gajim.org/gajim/gajim/issues
or in the
.Em gajim-devel
mailing list; if you want to send us a patch, please do so in our bug tracker.
You can also find us in our chat room.
.Sh WWW
https://www.gajim.org/
.Sh XMPP
You are welcome to join us at gajim@conference.gajim.org
.Sh MAILING LIST
Below are public mailing lists on lists.gajim.org
.Bd -literal -offset indent
https://lists.gajim.org/cgi-bin/listinfo/gajim-devel
https://lists.gajim.org/cgi-bin/listinfo/translators
.Ed
.Pp
More mailing lists at
.Bd -literal -offset indent
https://lists.gajim.org/cgi-bin/listinfo
.Ed
.Sh BUGS
Please submit bugs at https://dev.gajim.org/gajim/gajim/issues
.Sh SEE ALSO
.Xr gajim 1
